config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  post 'sessions/create'
  delete 'sessions/destroy'

  get 'oauth/callback'
  post 'oauth/post_tweet'

  resources :posted_photos, only: [:index, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/posted_photo.rb
class PostedPhoto < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def callback    
    session[:access_token] = fetch_access_token
    redirect_to posted_photos_path
  end

  def post_tweet
    uri = URI.parse("https://arcane-ravine-29792.herokuapp.com/api/tweets")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    headers = { 
      "Content-Type" => "application/json",
      "Authorization" => "bearer #{session[:access_token]}"
    }

    request_body = {
      text: tweet_params[:title],
      url: "http://localhost:3000/#{tweet_params[:image]}"
    }.to_json

    http.post(uri.path, request_body, headers)
  end

  private

  def fetch_access_token
    request_params = {
      client_id: 'd7c39097d19b5efe7fce7f8f4fe63ead3a6ba5b79fa09f0f60cc221e3fd03f0d',
      client_secret: 'fa7911ce9538873b1694d18a473be2d35d44cc620c1b73ccc1f889fed374e73a',
      redirect_uri: 'http://localhost:3000/oauth/callback',
      code: params[:code],
      grant_type: 'authorization_code'
    }
    uri = URI('https://arcane-ravine-29792.herokuapp.com/oauth/token')
    res = Net::HTTP.post_form(
      uri,
      request_params
    )
    JSON.parse(res.body)['access_token']
  end

  def tweet_params
    params.require(:posted_photo).permit(:title, :image)
  end
end

app/controllers/posted_photos_controller.rb
class PostedPhotosController < ApplicationController
  before_action :login_check

  def index
    @posted_photos = PostedPhoto.all.order(created_at: :DESC)
    @auth_req_url = auth_req_url
  end

  def new
    @posted_photo = PostedPhoto.new
  end

  def create
    file = posted_photo_params[:image]
    file_name = file&.original_filename
    @posted_photo = PostedPhoto.new(title: posted_photo_params[:title], image: file_name)
    if @posted_photo.save
      save_path = Rails.root.join('public/posted_photos', file_name)
      File.open(save_path, 'wb'){ |f| f.write(file.read) }
      redirect_to action: :index
    else
      render "new"
    end
  end

  private

  def posted_photo_params
    params.require(:posted_photo).permit(:title, :image)
  end

  def auth_req_url
    base_url = 'https://arcane-ravine-29792.herokuapp.com/oauth/authorize?'
    redirect_url_q = URI.encode_www_form(redirect_uri: 'http://localhost:3000/oauth/callback')
    response_type_q = URI.encode_www_form(response_type: 'code')
    client_id_q = URI.encode_www_form(client_id: 'd7c39097d19b5efe7fce7f8f4fe63ead3a6ba5b79fa09f0f60cc221e3fd03f0d')
    base_url + redirect_url_q + '&' + response_type_q + '&' + client_id_q
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to posted_photos_path if logged_in?
  end

  def create
    user = User.find_by(user_name: params[:session][:user_name].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to posted_photos_path
    else
      flash.now[:alert] = ['ユーザーIDを入力してください'] if params[:session][:user_name].blank?
      flash.now[:alert] = ['パスワードを入力してください'] if params[:session][:password].blank?
      flash.now[:alert] = ['ユーザーIDを入力してください', 'パスワードを入力してください'] if params[:session][:user_name].blank? && params[:session][:password].blank?
      flash.now[:alert] = ['ユーザーIDとパスワードが一致するユーザーが存在しません'] if user.nil?
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posted_photos_helper.rb
module PostedPhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_name] = user.id
  end

  def current_user
    if session[:user_name]
      @current_user ||= User.find_by(id: session[:user_name])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_name)
    @current_user = nil
  end

  def login_check
    redirect_to root_path unless logged_in?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnifaKadai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posted_photos/_posted_photo.html.erb
<div>
  <p><%= posted_photo.title %></p>
    <% if session[:access_token].present? %>
    <%= button_to 'ツイートする', oauth_post_tweet_path(posted_photo: { title: posted_photo.title, image: posted_photo.image }), method: :post %>
  <% end %>
  <%= image_tag "/posted_photos/#{posted_photo.image}" %>
</div>

app/views/posted_photos/index.html.erb
<%= render 'shared/logout_button' %>
<h1>写真一覧</h1>
<div>
  <%= link_to "MyTweetAppと連携", @auth_req_url %>
</div>
<div>
  <%= link_to "画像をアップロード", new_posted_photo_path %>
</div>
<div style='display: flex;'>
  <%= render partial: "posted_photo", collection: @posted_photos%>
</div>

app/views/posted_photos/new.html.erb
<%= render 'shared/logout_button' %>
<h1>写真アップロード</h1>
  <div style="color: red;">
    <ul>
      <% @posted_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<%= form_for(@posted_photo) do |f| %>
  <div>
    <%= f.label :title, "タイトル"%>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :image, "画像ファイル"%>
    <%= f.file_field :image %>
  </div>

  <%= f.submit 'アップロード' %>
  <%= link_to "キャンセル", posted_photos_path %>
<% end %>

app/views/shared/_logout_button.html.erb
<div>
  <%= link_to "ログアウト", sessions_destroy_path, method: :delete %>
</div>